spring.application.name=notification-service
server.port=8084

database.service.url=${DATABASE_SERVICE_URL:http://localhost:8083}

jwt.secret=bookshelf-idp-secret-key-minimum-32-chars
jwt.expiration=86400000

springdoc.api-docs.path=/v3/api-docs