spring.application.name=notification-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/bookshelf_notifications
spring.datasource.username=postgres
spring.datasource.password=your_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public

# CRITICAL: acelasi secret ca in auth-service pentru ca token-urile sa fie validate corect
jwt.secret=bookshelf-idp-secret-key-minimum-32-chars

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.jpa.open-in-view=false
